version: '3.8'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
    networks:
      app-net: {}

  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    networks:
      app-net: {}


  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
    networks:
      app-net: {}

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      app-net: {}

networks:
  app-net: {}

volumes:
  mongo-data:
