name: Deploy to EC2 with CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js for frontend
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install frontend dependencies
      run: npm install
      working-directory: frontend

    - name: Build the frontend
      run: npm run build
      working-directory: frontend

    - name: Set up Node.js for backend
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install backend dependencies
      run: npm install
      working-directory: backend

   
    - name: Deploy to EC2 with CodeDeploy for frontend
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
        AWS_REGION: 'ap-southeast-1'
        APPLICATION_NAME: 'your-frontend-application-name'
        DEPLOYMENT_GROUP_NAME: 'your-frontend-deployment-group-name'
      run: |
        aws deploy create-deployment \
          --application-name $APPLICATION_NAME \
          --deployment-group-name $DEPLOYMENT_GROUP_NAME \
          --s3-location bucket=my-bucket,key=my-key,bundleType=zip \
          --region $AWS_REGION

    - name: Deploy to EC2 with CodeDeploy for backend
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
        AWS_REGION: 'ap-southeast-1'
        APPLICATION_NAME: 'your-backend-application-name'
        DEPLOYMENT_GROUP_NAME: 'your-backend-deployment-group-name'
      run: |
        aws deploy create-deployment \
          --application-name $APPLICATION_NAME \
          --deployment-group-name $DEPLOYMENT_GROUP_NAME \
          --s3-location bucket=my-bucket,key=my-key,bundleType=zip \
          --region $AWS_REGION
